version: '2.2'

services:
  docker-host:
    image: qoomon/docker-host:2.4.2
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  postgres_backend:
    image: postgres:12.2
    container_name: postgres_backend
    ports:
      - "5433:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=git_changes
    healthcheck:
      test: ["CMD-SHELL", "psql -w -U postgres -d git_changes -c SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    image: docker.pkg.github.com/egorklimov/git-changes-monitoring/git-changes-monitoring-frontend:latest
    ports:
      - 3000:80 # Frontend HTTP server port
  backend:
    image: docker.pkg.github.com/egorklimov/git-changes-monitoring/git-changes-monitoring-backend:latest
    ports:
      - 8080:8080 # Backend HTTP server port
    depends_on:
      postgres_backend:
        condition: service_healthy
