name: Publish Backend Docker image
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        working-directory: git-changes-monitoring-backend
        run: mvn clean package -DskipTests
      - name: Publish backend to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: egorklimov/git-changes-monitoring/git-changes-monitoring-backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          context: ./git-changes-monitoring-backend
          dockerfile: ./git-changes-monitoring-backend/src/main/docker/Dockerfile.jvm
