name: Publish Frontend Docker image
on: ["push"]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push Frontend image to GitHub Packages
        working-directory: git-changes-monitoring-frontend
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          file: .//Dockerfile
          repository: egorklimov/git-changes-monitoring/git-changes-monitoring-frontend
          tag_with_ref: true
